# Generated by Django 4.1.7 on 2023-04-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to=None, verbose_name='Header-img')),
                ('hero_text', models.TextField(max_length=1500, verbose_name='İçerik')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to=None, verbose_name='Dizi-Film')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
    ]
