# Generated by Django 4.1.7 on 2023-04-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_post_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hero_text',
        ),
    ]
