# Generated by Django 4.1.7 on 2023-04-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
