# Generated by Django 4.1.7 on 2023-04-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('image', models.ImageField(upload_to=None, verbose_name='Dizi-Film')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
