# Generated by Django 4.1.7 on 2023-04-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_alter_post_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(verbose_name='Göster'),
        ),
    ]
